mirror-media/mirror-media-nuxt

- .drone.yml
- .kube.yml
- Dockerfile
I have added the drone pipeline for DEV deployment.
> feat: add drone pipeline files

- jest.config.js
- layouts/default.vue
- nuxt.config.js
> build: modify default extentions to leave off .js only

- package.json
- server/index.js
- yarn.lock
> feat: add helmet for security issue

- api/headers.js
- nuxt.config.js
- 設置測試機的 response header
- 設置首頁、列表頁面的 response header
- 設置文章頁面的 response header
參照 #13
> feat: set specific url response header

- .eslintrc.js
resolve https://github.com/mirror-media/mirror-media-nuxt/issues/17
> style: change vue/attribute-hyphenation rule to never

- nuxt.config.js
作法根據：[Allow ga's id be a function #27](https://github.com/nuxt-community/analytics-module/issues/27 )
> feat: set GA ID according to domain

- package.json
- yarn.lock
resolve https://github.com/mirror-media/mirror-media-nuxt/issues/37
usage boilerplate:
```vue
<template>
<div>
<client-only>
<infinite-loading />
</client-only>
</div>
</template>
<script>
import InfiniteLoading from 'vue-infinite-loading'
export default {
components: {
InfiniteLoading,
},
}
</script>
<style lang="sass" scoped></style>
```
> build: add vue-infinite-loading package

- test/helpers/createWrapperHelper.js
resolve #42
檔案擺放方式參考：https://github.com/vuejs/vue/tree/dev/test/helpers
usage boilerplate：
```js
import createWrapperHelper from '~/test/helpers/createWrapperHelper'
import Component from 'Component.vue'
const defaultMountingOptions = {
mocks: {
$router: {
push: jest.fn(),
},
$ga: {
event: jest.fn(),
},
},
}
const createWrapper = createWrapperHelper(defaultMountingOptions)
describe('', () => {
test('', () => {
const overrideMountingOptions = {
propsData: {
foo: 'foo',
},
mocks: {
$store: {
commit: jest.fn(),
},
},
}
const wrapper = createWrapper(Component, overrideMountingOptions)
/* create a wrapper with mounting options:
{
propsData: {
foo: 'foo',
},
mocks: {
$router: {
push: jest.fn(),
},
$ga: {
event: jest.fn(),
},
$store: {
commit: jest.fn(),
},
},
}
*/
})
})
```
> test: add createWrapperHelper

- jest.config.js
- pages/section/_name.vue
For more info about https://github.com/mirror-media/mirror-media-nuxt/pull/61/commits/69f2170ecba354a3feb7d09a8a0607a6280814d7 , please check https://github.com/vuejs/vue-jest/issues/199
> feat: section page color theme

- components/UIArticleCard.vue
- components/__tests__/UIArticleCard.spec.js
- layouts/default.vue
- pages/__tests__/section.topic.spec.js
- pages/section/topic.vue
1. 新增 `/section/topic` 頁面。
2. 新增 `UIArticleCard.vue` component 一項功能：若 props `imgText` 為 empty string，自動隱藏。
> feat: section topic page

- plugins/vuePluginsGlobal.js
- enable VueLazyload lazy component feature for lazy load iframe
> feat: enable VueLazyload lazy component feature

- components/__tests__/UIArticleCard.spec.js
- components/__tests__/UIArticleList.spec.js
- components/__tests__/UIFooter.spec.js
- components/__tests__/UIHeaderNavSection.spec.js
- components/__tests__/UIHeaderNavTopic.spec.js
- components/__tests__/UISearchBar.spec.js
- components/__tests__/UISearchBarDesktop.spec.js
- components/__tests__/UISearchBarInput.spec.js
- components/__tests__/UISearchBarSelect.spec.js
- pages/__tests__/search.spec.js
參考 https://vue-test-utils.vuejs.org/api/wrapper/#get
> test: change wrapper method "find" to "get" for an element that should exist

- components/UIVideoCategory.vue
- pages/__tests__/section.videohub.spec.js
- pages/section/videohub.vue
- use backend api
- process response data to correct props format
- fix the first item style in video category block when block height is not high enough
> feat(video): use backend api and process response data

- nuxt.config.js
- package.json
- pages/__tests__/video.spec.js
- pages/video/_id.vue
- yarn.lock
- 實作單一影音的頁面
- 引入 `@nuxtjs/dayjs` 做日期時間格式處理
- `isValidYoutubeVideo `, `restructureAndFilterItems `, `restructureItem ` 這 3 個方法未來會重構並挪到 `utilities` 中共用
> feat(video): add single page

- components/ContainerHeader.vue
- plugins/gpt-ad/index.vue
- plugins/gpt-ad/util.js
- fix adWidth value due to function name issue
- remove debug log
> fix(GPTAD): fix adWidth value due to function name issue

- components/UIShareLine.vue
- components/UIVideoCategory.vue
- components/__tests__/UIShareLine.spec.js
- constants/index.js
- pages/section/videohub.vue
- pages/video_category/_name.vue
- let category block title can link to category page
- adjust category page amount of items per row
- fix line share href
> feat(videohub): update video pages

- api/headers.js
- components/UICulturePostIndex.vue
- components/UIParagraphWithAnnotation.vue
- pages/culture-post/_slug.vue
- add culture-post cache control
- remove unnecessary code
- replace site url by constant
- replace duplicate share feature by components
- rename meaningless variable naming
> feat: add culture-post cache control and remove unnecessary code

- api/combo.js
- nuxt.config.js
修改原本的 `/api/combo?endpoint=sections` 流程如下
1. 先去特定位址拿 static json，若有任何錯誤進入下一個步驟。
2. 實際去打 restful api 的 `/api/combo?endpoint=sections`，取得 api response。
> feat(api): fetch json when encounter /api/combo?endpoint=sections

- nuxt.config.js
> fix(meta): fix head meta errors

- components/UIStoryBody.vue
- components/UIStoryContentHandler.vue
將本來文章頁針對內文的樣式，抽成 class，並以 `story--` 開頭放置到 `UIStoryBody.vue` 另一個沒有 scoped 的 `<style>` 中
@kwhsiung @yeefun  兩位看過後有其他想法再提出來吧
> refactor(story): abstract out style to class attribute

- nuxt.config.js
- package.json
- plugins/requests/index.js
Bump the version to clear redis cache.
> chore: release

- components/UiStoryVideo.vue
- components/culture-post/UiTheCover.vue
> feat: set video autoplay in wide style

- components/UiStoryVideo.vue
- components/culture-post/UiTheCover.vue
> feat: remove video control bar and add looping feature in wide style

- package.json
> chore: bump version to 1.18.0

- components/UiEmbeddedCode.vue
- components/UiStoryContentHandler.vue
> fix: fix embedded code display problem

- components/culture-post/ContentHandler.vue
修正 wide 版型的 embedded code 顯示問題
> fix: fix embedded-code display problem in wide style

- components/culture-post/UiArticleIndex.vue
- components/culture-post/UiTheCover.vue
修正 premium 頁 fb、line 標籤無法點擊的問題
> fix: fix the click problem of sns icons

- static/ads.txt
新增 ads.txt 檔案，已完成 dable 更新需求。
文件：https://drive.google.com/file/d/1URsCz-vC2Q5s8fuBvrS0p9tIuu1D_BPA/view
> feat: add ads.txt file for dable

- static/ads.txt
> fix: remove ads.txt file

- components/SubscribeFail.vue
- components/SubscribeFailWrapper.vue
- components/SubscribeSuccess.vue
- components/SubscribeSuccessOrderInfo.vue
- components/SubscribeSuccessOrderInfoContentRow.vue
- pages/subscribe-magazine/index.vue
重發一次 ><
主要更動：
紙本雜誌訂閱頁面顯示
幾個不確定的部分：
1.  成功頁面的日期用 new Date()
2. 附註和續訂戶代碼的資料來源不確定
> feat: subscribe results

- components/SubscribeFailWrapper.vue
- components/SubscribeSuccessOrderInfo.vue
- components/SubscribeSuccessOrderInfoContentRow.vue
1. 讓失敗頁面按鈕可以導回首頁
2. 成功頁面資料名稱更改
> feat(subscribeResult): add link to home and fix success data

- components/UiArticleList.vue
1. 修正周子飛文章導向問題
2. 因測試機環境無法操作搜尋，須至正式機環境驗證
> fix: fix the redirect problem of zhou-zhi-fei

- components/UiHeaderNavSection.vue
- components/culture-post-for-premium/ContainerCulturePost.vue
- components/culture-post-for-premium/UiArticleInfo.vue
1. （會員頁）特約記者須於前台顯示
2. （會員頁）記者、攝影 呈現由「/」 改為 「｜」
3. （navigation）「會員專區」navigation 手機版UI調整
> feat: navbar member section mobile style adjust and member post other author

- components/culture-post-for-premium/UiArticleInfo.vue
> fix(UiArticleInfo): show extendByline

- utils/article.js
> fix: change type name from project to projects

- components/PurchasedList.vue
- components/SubscribeSuccess.vue
- components/SubscribeSuccessOrderInfo.vue
- components/UiSubscribeInfo.vue
**說明**
- 紙本雜誌訂閱成功頁面 UI 微調
**參考資料**
- [Asana 卡片](https://app.asana.com/0/1200570778319695/1200582951827915)
- [文件](https://paper.dropbox.com/doc/jgnC27r3xclTCRRfCdqUi#:h2=UI-%E8%AA%BF%E6%95%B4)
- 路由：`/papermag/result` （須從 `/papermag` 進入）
> style: magazine-subscribe success UI adjust

- components/SubscribeFail.vue
描述
- 更改紙本雜誌訂閱失敗頁面的聯絡電話。
參考資料
[文件](https://paper.dropbox.com/doc/--BOeu6_pWrnnODTL_uh_hr1e7Ag-jgnC27r3xclTCRRfCdqUi#:h2=%E8%A8%82%E5%96%AE%E5%A4%B1%E6%95%97%E9%A0%81-/--%E4%BB%98%E6%AC%BE%E5%A4%B1%E6%95%97%E9%A0%81)
[任務卡片](https://app.asana.com/0/1200570778319695/1200581556792672)
> feat(SubscribeFail): change fail message phone number

- components/SubscribeFormAcceptPermission.vue
- components/SubscribeFormReceipt.vue
- components/UiSubscribeSelect.vue
- components/UiValidationInput.vue
- 更改說明文字
- 更改下拉式選單樣式
- 二聯式發票二聯式發票：第一欄選項改變的時候，第二欄應該要清空，第二欄要驗證輸入內容
- 三聯式發票統編輸入 8 碼，不足 8 碼就顯示輸入錯誤
- 取消預設選項
- 沒做選擇，跳出警告紅字，無法送出表單
- [卡片](https://app.asana.com/0/1200570778319695/1200581556792680)
> feat: adjust receipt area

- components/SubscribeFormEditPerchase.vue
- components/UiMerchandiseList.vue
修正 pop-up isDisable 判定時出錯的問題。
[相關 PR](https://github.com/mirror-media/mirror-media-nuxt/pull/347#issue-693362372)
> fix: isDisable and setCount function

- components/PurchasedList.vue
- components/SubscribeChoosePlan.vue
- components/SubscribeChoosePlanCard.vue
- components/SubscribeDiscount.vue
- components/SubscribeForm.vue
- components/SubscribeFormEditPerchase.vue
- components/SubscribeFormPerchaseInfo.vue
- components/SubscribeFormPlanList.vue
- components/SubscribeSimFormStatus.vue
- components/SubscribeSuccessOrderInfo.vue
- components/UiMerchandiseList.vue
- pages/papermag/_plan/index.vue
- pages/papermag/redirect/index.vue
- pages/papermag/result/index.vue
- yarn.lock
- 勾選「我有續訂折扣碼」出現輸入續訂代碼區塊。
- 輸入滿五個數字後，可按「使用」送出。
- 成功後下方出現折扣。
- 側欄「訂單資訊」出現折扣價錢和額外贈送期數。
- 運費價錢調整，以一期 20 元計算。
- 在成功頁顯示折扣碼、折扣價錢和調整後的運費。
- [卡片](https://app.asana.com/0/1200570778319695/1200581556792678)
新增二聯式發票驗證欄位、修改手機號碼驗證
> feat: discount input and show

- components/SubscribeFormEditPerchase.vue
- components/UiMerchandiseList.vue
- components/UiSubscribeButton.vue
- components/UiSubscribeCountButton.vue
- 「單價」欄位顯示每份價錢 * 數量
- 加減按鈕 UI 調整
- 確認按鈕 disabled 狀態和 UI
> fix: adjust pop-up

- components/SubscribeFormOrdererData.vue
- 修正手機驗證無法正常顯示
- 增加 input placeholder
> Fix: cellphone validation

- yarn.lock
Reverts mirror-media/mirror-media-nuxt#353
> Revert "fix: yarn.lock"

- yarn.lock
> fix: @nuxt/config

- pages/papermag/result/index.vue
> fix: fail-button redirect path

- components/SubscribeChoosePlan.vue
- components/SubscribeForm.vue
- components/SubscribeFormEditPerchase.vue
- components/SubscribeFormPlanList.vue
- components/UiMerchandiseList.vue
- 修改方案選擇頁品項 wording ，拿掉附贈期數。
- 修改手機版 pop-up 品項寬度。
> feat: advise perchasePlan detail wording and pop-up flex

- components/SubscribeFormPlanList.vue
- components/SubscribeSuccessOrderInfo.vue
- 修改折扣碼手機版 UI
- 修改折扣扣碼前綴：「MR000」
> fix: discount-code mobile UI advise and change wording

- components/SubscribeFormOrdererData.vue
- components/SubscribeStepProgressStep.vue
- 更改手機版方案選擇破版問題
- 更改收件人資訊 wording
> fix: advise step UI & orderer-data detail wording

- components/SubscribeForm.vue
- components/SubscribeFormPlanList.vue
- components/UiMerchandiseList.vue
描述：
- 修改購買清單的 UI
- 更改購買清單 wording
> style: merchandise-list UI

- components/SubscribeChoosePlan.vue
- components/SubscribeChoosePlanCard.vue
- components/SubscribeForm.vue
- components/SubscribeFormEditPerchase.vue
- components/SubscribeFormPlanList.vue
- components/UiMerchandiseList.vue
描述：
- 更改價格 2800 >> 2880，5200 >> 5280
> feat: change price

- components/UiFooter.vue
- components/culture-post-for-premium/UiArticleBody.vue
- constants/index.js
- 會員文章文末加文字及引導連結
- 調整 footer 樣式及內容
- [Asana 卡片](https://app.asana.com/0/1200640136089459/1200581396911951)
- [設計稿](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A---%E7%B6%B2%E7%AB%99?node-id=3305%3A12284)
> feat: premium-article copyright link & adjust footer

- components/UiFooter.vue
- 修改 footer 字級大小
- [Asan 卡片](https://app.asana.com/0/0/1200581396911968/1200701844579260/f)
> style(UiFooter): footer font-size

- components/UiSubscribeCountButton.vue
- 修改 count-button 的樣式以在 windows 符合設計稿
- [Asana卡片](https://app.asana.com/0/1200640136089459/1200683061054603/f)
> fix: adjust count button

- pages/loginNew.vue
- pages/service-rule.vue
- 新增「服務條款」頁面
- 若曾勾選過同意條款，則紀錄於 cookie 中
- 進入登入頁面時檢查是否有 cookie 紀錄，若沒有則進入服務條款頁面
- 勾選後會回到登入頁面，並照樣於登入後回到原本在閱讀的頁面
- `/login` 和 `/loginNew` 的差別？
- 目前只有 `newLogin.vue` 的檔案有檢查，看起來所有頁面都會經過 `/login` ，這樣還有其他 page 也需要檢查嗎？
- [Asana 卡片](https://app.asana.com/0/1200640136089459/1200546112820288)
- [設計稿](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A---%E7%B6%B2%E7%AB%99?node-id=3277%3A11196)
> feat: create survice-rule page and check if read before login

- components/MembershipFormPerchaseInfo.vue
- components/MembershipFormPlanList.vue
- components/MembershipInfoSim.vue
- components/UiMembershipList.vue
- pages/subscribe/info.vue
- 會員訂閱訂購確認頁 UI
- 模擬器調控是否需要驗證 / 訂單是否成功
- [Asana 卡片](https://app.asana.com/0/1200720395792829/1200520483300778)
- [會員訂閱頁面 PRD](https://paper.dropbox.com/doc/PRD--BPzlvJ_sLZ33TAcqn4wia7_TAg-r3yPzn9K2wU5fUI5cy37F)
- [設計稿](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A---%E7%B6%B2%E7%AB%99?node-id=2822%3A6801) / 2.2 處
> feat: subscribe-info page

- pages/profile/purchase.vue
> fix: sim condition

- pages/subscribe/index.vue
- 新增會員訂閱 -> 方案選擇頁 -> 年訂閱會員（2.1.4）
- [Asana 卡片](https://app.asana.com/0/1200640136089459/1200581396911923)
- [會員訂閱頁面 PRD](https://paper.dropbox.com/doc/PRD--BPzlvJ_sLZ33TAcqn4wia7_TAg-r3yPzn9K2wU5fUI5cy37F)
- [設計稿](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A---%E7%B6%B2%E7%AB%99?node-id=2822%3A6801)
> feat: subscribe-choose page year member section

- pages/profile/purchase.vue
- 購買紀錄頁（/profile/purchase）wrapper 樣式調寬
#379
> style: puechase-page wrapper

- components/MemberShipStatus.vue
- 訂購紀錄頁的「升級為年訂閱方案」改為「變更為年訂閱方案」
[設計稿](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A-%E7%B6%B2%E7%AB%99?node-id=2978%3A11490)
> fix: change change-plan-button wording

- components/MemberShipStatus.vue
- basic 會員的按鈕改為「升級 premium 會員」
- [設計稿](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A---%E7%B6%B2%E7%AB%99?node-id=2822%3A6801)
> fix: change basic number status button

- pages/service-rule.vue
- 調整「使用條款」頁面，讓 desktop 版本和手機版相同
- [設計稿](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A---%E7%B6%B2%E7%AB%99?node-id=4184%3A13669)
> style: service-rule desktop style same as mobile

- components/ContainerLoginForm.vue
- components/ContainerLoginFormInitial.vue
- pages/loginNew.vue
- 登入頁UI調整（由於您曾以 Google 帳號登入，請點擊上方「以 Google 帳號繼續」重試。）
- 因為還沒串資料，新增模擬器，模擬器將於正式機被隱藏。
- [Asana 卡片](https://app.asana.com/0/1200720395792829/1200728557699980)
- [設計稿](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A---%E7%B6%B2%E7%AB%99?node-id=4228%3A14294)
> feat: login hint UI

- pages/email-verify.vue
- 修改信箱驗證頁面模擬器顯示條件，使其在正式機外地方皆會顯示
#386
> fix: email-varify sim show when ENV !== show

- pages/email-verify.vue
- 新增「email認證頁UI」的 email 不可更改狀況。
#386
> feat: add unalterable-email situation and sim

- api/member-subscription-proxy.js
- nuxt.config.js
已在config（dev）中新增apiGateWay的api
> feat: add new gateway-api to fetch member-subscription data

- pages/marketing.vue
- 新增 marketing 頁面 UI
- 測試網址：`/marketng`
- [設計稿](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A---%E7%B6%B2%E7%AB%99)
- [Asana](https://app.asana.com/0/1200896349481613/1200956987099971)
> feat: add marketing page

- components/MicroAdWithLabel.vue
- pages/story/_slug.vue
- 調整文末廣告「特企」標籤 z-index，讓其不會擋住其他部分。
> style: ad-lable z-index adjust

- components/ContainerStoryBody.vue
Reverts mirror-media/mirror-media-nuxt#401
搞錯需求
> Revert "style(ContainerStoryBody): brief color"

- components/ContainerStoryBody.vue
- components/culture-post-for-premium/UiArticleBody.vue
- components/culture-post-for-premium/UiPremiumBrief.vue
- 更改會員文章短文樣式
- [設計稿](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A---%E7%B6%B2%E7%AB%99?node-id=3305%3A12947)
> style: premium brief style

- components/culture-post-for-premium/UiPremiumBrief.vue
> style: brief paragraph margin top

- components/UiSubscribeInfo.vue
- pages/profile/purchase.vue
- pages/subscribe/index.vue
- pages/subscribe/info.vue
- pages/subscribe/success.vue
- 會員訂閱 UI debug
- [debug safari 2.3付款成功頁 按鈕無間隔](https://app.asana.com/0/1200896349481613/1201083134543998)
- [debug  2.2確認訂購頁 / 2.3 付款結果頁年訂閱狀態，文字敘述錯誤](https://app.asana.com/0/1200896349481613/1201083134543993)
- [UI 調整 2.1 方案選擇頁 注意事項調整距離 ](https://app.asana.com/0/1200896349481613/1201083134544003)
- [debug  Android 3.1 付款紀錄頁-Basic會員狀態 按鈕跑版](https://app.asana.com/0/1200896349481613/1201083134543997)
- [設計稿](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A---%E7%B6%B2%E7%AB%99?node-id=2822%3A6801)
> fix: debug subscribe UI and wording

- pages/subscribe/info.vue
- 會員訂閱確認訂購頁，填入email欄位需帶預設值，且可被更動
- [Asana 卡片](https://app.asana.com/0/1200896349481613/1201112591842143)
> feat: subscribe-info page email preset membership email

- components/SubscribeSuccessOrderInfo.vue
- pages/subscribe/success.vue
> feat: remove orderDate

- cloudbuild.yaml
Reverts mirror-media/mirror-media-nuxt#413
> Revert "perf(ci): use N1_HIGHCPU_32 for cloud build"

- components/SubscribeStepProgress.vue
- pages/subscribe/success.vue
- 會員訂閱：步驟三的「付款完成」改成「訂單完成」
- 會員訂閱：「您已完成變更方案，以下為本次變更資訊，您的新方案將於下期開始進行。」 => 「訂單處理中，請稍候在訂閱紀錄確認訂單狀況」
> fix: adjust wording

- components/culture-post-for-premium/UiSectionLabel.vue
- 會員文章標籤連結修正
- 相關 commit： #439
> fix: premium label link
