mirror-media/mirror-media-nuxt

jest.config.js
nuxt.config.js
package.json
pages/index.vue
server/index.js
yarn.lock

- upgrade `babel-jest`, `cross-env`, `eslint-plugin-prettier`, `jest`, `nodemon` and `prettier` version
- fix prettier `trailingComma ` error due to `prettier` 2.0 change
https://github.com/orgs/mirror-media/teams/front-end/discussions/4

feat: upgrade packages version

---

layouts/default.vue
nuxt.config.js
package.json
sass/_breakpoints.sass
sass/_variables.sass
yarn.lock

This PR will resolve https://github.com/mirror-media/mirror-media-nuxt/issues/14.
- 新增 [@nuxtjs/style-resources](https://github.com/nuxt-community/style-resources-module) package，我們可以直接在 component 中使用任何 sass 全域共用屬性而不用手動 `@import`。
- 新增 `~/sass/` 資料夾，`~/sass/*.sass` 中的屬性皆套用全域共用效果。
- 新增 `~/sass/_variables.sass`，目前僅存放此 PR 會使用到的 breakpoints。
- 參考來源：https://github.com/twbs/bootstrap/blob/28cb1ff2b23253293601c51aff434c39b461025e/scss/_variables.scss#L280
- 由於我們並不會使用到 `992px(lg)` breakpoint，故暫先移除。
- 新增 `~/sass/_breakpoints.sass`，存放此 PR 會使用到的 breakpoint mixins。
- 參考來源：https://github.com/twbs/bootstrap/blob/c5b1919deaf5393fcca9e9b9d7ce9c338160d99d/scss/mixins/_breakpoints.scss
- 使用方式參考：
```sass
/* css properties of mobile */
#test
color: red
/* NOT A DEFAULT QUERY, add when we want to handle …
```

feat: breakpoints mixins

---

api/constant.js
api/headers.js
api/index.js
nuxt.config.js
package.json
server/index.js
yarn.lock

- 串 tr-project-rest API
- 設定 `/api` 的 cache-control
- 將共用的 header 規則移到 `api/constant.js` (檔案名稱可討論)
需新增 config 請留意 slack 訊息或看 paper 文件

feat: add api route to connect backend

---

components/UIHeaderNavSection.vue
scss/_variables.scss

1. 將 `$sections-color` 加入至 `scss/_variables.scss`，使得各 component 中的 scss style 可以共用。
2. 新增 `:export` 於 `scss/_variables.scss`，使得 js 可以 import 並利用，但由於應該是無法直接 export scss map 給 js 使用，所以需要將其分解，js 中的使用方式請參考：
```js
import variables from '~/scss/_variables.scss'
console.log(variables)
// {
//   sections-color-businessmoney: "#009045",
//   sections-color-carandwatch: "#003153",
//   sections-color-culture: "#009245",
//   sections-color-entertainment: "#bf3284",
//   sections-color-external: "#ee5a24",
//   sections-color-foodtravel: "#eac151",
//   sections-color-international: "#911f27",
//   sections-color-mafalda: "#662d8e",
//   sections-color-news: "#30bac8",
//   sections-color-people: "#efa256",
//   sections-color-videohub: "#969696",
// }
```

refactor: section colors

---

nuxt.config.js
package.json
plugins/requests/__tests__/index.spec.js
plugins/requests/index.js
yarn.lock

Resolve #41 
用法基本上根據討論結果來實作
- 討論當時沒有注意到的狀況：在 `where` 下使用 `$or` 的用法
`/getposts?where={"$or":[{"writers":"584fb40ab854000d002d23cb"},{"photographers":"584fb40ab854000d002d23cb"},{"camera_man":"584fb40ab854000d002d23cb"},{"designers":"584fb40ab854000d002d23cb"},{"engineers":"584fb40ab854000d002d23cb"}]}`
因此有針對 `$or` 做特別處理，用法可以參考測試
- 由於 tr-project-rest 的風格不一致，因此有特別處理 `isAudioSiteOnly`
- 考量 `snakeCase`, `axiosGet`, `buildParams` 只會在這裡有使用需求，就沒有另外分到其他檔案
- 注意 `fetchTag`, `fetchTimeline` 的使用狀況跟其他不一樣，接受的參數是 `id`，可以參考 API 使用文件
使用範例：
```
async fetch() {
try {
const xxx = await this.$fetchCombo({ endpoint: 'sections' })
} catch (error) {
// error.code 判斷 404 還是 500
}
}
```
```
// promise version
mounted () {
this.$fetchCombo({ endpoint: 'sections' })
.then((res) => {
// to do
})
.catch(error => {
// …
```

feat: add request plugin

---

components/UIInfiniteLoading.vue
layouts/default.vue
pages/__tests__/author.spec.js
pages/__tests__/category.spec.js
pages/__tests__/section.spec.js
pages/author/_id.vue
pages/category/_name.vue
pages/section/_name.vue

- 新增 `/category/:name` 與 `/author/:id` routes 對應之 page components 及對應測試。
- Notes:
- 上述兩個 routes 與 `/section/:name` 之 html template 與 data-binding 邏輯相同，唯有 data fetching 與 data processing 邏輯稍有差異。
- 由於上述原因，目前以下 page component 及對應測試有大量重複程式碼，由於目前 listing 頁面尚缺 `/topic/:id`, `/section/topic` 與 `/search/:query` 頁面尚未實作，待所有情境皆實作完成再來考慮針對重複的程式碼重構。
- `/page/section/_name.vue`
- `/page/category/_name.vue`
- `/page/author/_id.vue`

feat: add listing category and author page

---

plugins/requests/index.js

對應目前後端新開的 search endpoint：
`http://api.mirrormedia.mg/search?keywords={要搜尋的關鍵字}&section={時事/最新/瑪法達/財經理財/}`

feat: add keywords and section in firstTier in buildParams

---

layouts/default.vue
pages/__tests__/search.spec.js
pages/__tests__/section.spec.js
pages/search/_keyword.vue

- 新增 `/search/:keyword?section={sectionId}` 頁面。
- 本頁之 loadmore 功能採手動方式，非無限捲軸，故有一個 loadmore button。
- 第一頁後的資料呈現待進行 api 串接。

feat: listing search page

---

.eslintrc.js
components/__tests__/ContainerHeader.spec.js
components/__tests__/UIArticleList.spec.js
components/__tests__/UIOthersList.spec.js
components/__tests__/UISearchBar.spec.js
components/__tests__/UISearchBarDesktop.spec.js
components/__tests__/UISearchBarInput.spec.js
components/__tests__/UISearchBarSelect.spec.js
components/__tests__/UISearchBarWrapper.spec.js
package.json
pages/__tests__/author.spec.js
pages/__tests__/category.spec.js
pages/__tests__/search.spec.js
pages/__tests__/section.spec.js
pages/__tests__/section.topic.spec.js
yarn.lock

- 升版 @vue/test-utils，基於該升版，有以下修正：
- 替換 `find ` 用於 component 的狀況，改使用 `findComponent `, ref [[1]](https://vue-test-utils.vuejs.org/api/wrapper/find.html) [[2]](https://vue-test-utils.vuejs.org/api/wrapper/#findcomponent)
- 省略 `await wrapper.vm.$nextTick()`：~實際上只有 `UISearchBarInput.spec.js` 省略掉後可以通過測試，而且個人覺得這個測試省略掉後仍有機會失敗，因此先用註解的方式，而其他的測試都沒有省略 `await wrapper.vm.$nextTick()`~
- 修正 `.eslintrc.js` 語法風格

build: upgrade @vue/test-utils and update api usage

---

jest.config.js
nuxt.config.js
pages/index.vue
plugins/gpt-ad/__tests__/gpt-ad.spec.js
plugins/gpt-ad/index.js
plugins/gpt-ad/index.vue
plugins/gpt-ad/util.js
plugins/vuePluginsGlobal.client.js
plugins/vuePluginsGlobal.js

Vue plugin for [Google Publisher Tag](https://developers.google.com/doubleclick-gpt/guides/get-started)，此 plugin 會 install 一個 global component: GPTAD
- component mounted 前會 insert gpt.js external script，不需要手動全局引入額外的 script。
- 我們可以透過 `v-if` 來控制是否需要 mount GPTAD component，達到按頁面需求 insert external script 的功能。
- [預設開啟 gpt ad lazy-loading 功能](https://developers.google.com/doubleclick-gpt/samples/lazy-loading)。
目前設計的使用方式如下，再請 @hsuehyungtan 和 @yeefun review:
```js
import Vue from 'vue'
import GPTAD from './gpt-ad'
Vue.use(GPTAD, {
adNetwork: '40175602',
})
```
```vue
<template>
<client-only>
<GPTAD
:adUnit="'test_mirror_pc_fin_970x250_HD'"
:adSize="[970, 250]"
/>
</client-only>
</template>
```

feat: gpt-plugin

---

components/UIYoutubeSubscribe.vue

- fix subscribe button not init due to `nuxt-link`
- use `lazy-component` for lazy load
- add `defer` attribute to `platform.js` script

fix: subscribe button not init due to nuxt-link

---

pages/__tests__/category.spec.js
pages/category/_name.vue
store/__tests__/sections.spec.js
store/sections.js

- 在 store 新增 `sectionByCategoryName` getter（作為方法），並以此 getter 重構 `pages/category/_name.vue`。
- rename：將 `current` 前綴詞去掉。category 頁面裡只會有一個 category 跟 section，且不會隨時間變動，**current** 的意涵已經夠清楚，應不需再提示讀者。

refactor: move common method sectionByCategoryName form page to store

---

plugins/requests/index.js

目前的 [`/tags/:id` api response](http://104.199.190.189:8080/tags/581e9c0acb9d9e0e0023ecaa) 會無法通過 `hasData` 的檢查，所以會非預期的回報 Not Found error，故暫時先新增對於 tags endpoint 的通過條件。

feat: add hasData validation for /tags api in fetchAPIData

---

constants/gptUnits.js

將 4 個共用的 GPT Unit ID 抽出來到 `global`
- `LOGO` 維持原本取名
- `MBCVR` 改為 `MB_FULL_SCREEN_FIRST `
- `MBCVR2` 改為 `MB_FULL_SCREEN_SECOND `
- `MBCVR3` 改為 `MB_FULL_SCREEN_THIRD `
若取名上有更好的想法，可以提供一下，`CVR` 改為 `FULL_SCREEN` 的原因是行銷單位的蓋板用語為 full screen ads

chore: update gpt unit constant

---

components/UIVideoIframeWithItems.vue
pages/__tests__/category.video_coverstory.spec.js
pages/category/video_coverstory.vue
pages/section/videohub.vue

- 實作影音的 category 頁，目前只建立其中一個 category，其他 category 頁基本上邏輯都一樣，待未來 listing 頁重構後，一起進行規劃
- 影音頁共用的一些常數或方法，會在之後的 PR 重構拆出來，例如：`PLAYLIST_MAPPING `, `isValidYoutubeVideo` , `processItems ` , `restructureItem`

feat(video): add video category page

---

components/MicroAd.vue
components/UIArticleList.vue
constants/microAdUnits.js
pages/author/_id.vue
pages/category/_name.vue
pages/section/_name.vue
pages/tag/_id.vue

雖然原本有提供 MicroAd 樣式，但未來樣式都會以寫在 `MicroAd.vue` 中為準，目前只加上 listing 原生廣告的樣式，而部分樣式仍然需要新增在所使用到 pages 中
就看你們對於 MicroAd 的設置，有沒有其他想法

feat(microAd): add microAds on listing page (exclude topic listing)

---

components/UIArticleList.vue
components/__tests__/UIArticleList.spec.js

參考頁面：https://nuxt-dev.mirrormedia.mg/section/businessmoney
issue：
由於各 listing 頁 loadmore 至第二頁時，`UIArticleList` 並沒有將 MicroAd 塞入 slot，以至於會有預留給 MicroAd slot 的空洞。
所以我加上了判斷，若 `UIArticleList` 沒有使用任何 listing MicroAd named slot 時，則不 render 預留給 MicroAd 的 list item wrapper。並補上相關測試供參考。

feat(UIArticleList): render list item of MicroAd conditionally

---

components/ContainerHeader.vue
components/UISearchBar.vue

Fix the issue reported by Lighthouse.
https://web.dev/button-name/?utm_source=lighthouse&utm_medium=cli

fix: buttons do not have an accessible name

---

components/UIArticleListFocus.vue
components/UIHeaderNavTopic.vue
components/UIOthersList.vue
components/UISidebar.vue
components/UIVideoCategory.vue
components/UIYoutubePolicies.vue

Fix the issue reported by Lighthouse.
https://web.dev/external-anchors-use-rel-noopener/?utm_source=lighthouse&utm_medium=cli

fix: links to cross-origin destinations are unsafe

---

nuxt.config.js

Fix the issue reported by Lighthouse.
https://web.dev/html-has-lang/

fix: <html> element does not have a [lang] attribute

---

components/UIShareFacebook.vue
components/UIShareLine.vue
components/__tests__/UIShareFacebook.spec.js
components/__tests__/UIShareLine.spec.js
composition/share.js
jest.config.js
nuxt.config.js
package.json
yarn.lock

在做文章頁的浮動分享時，發現功能跟之前做的 `Share*` components 一樣，但樣式不同，而且牽扯到生命週期 `mounted`，難以抽取出來共用，因此就決定引進 Composition API，重構這個部分。
這一個 commit 只有重構，之後會把這裡的 composition functions 用在浮動分享上。

refactor: extract social shares into composition functions

---

components/MicroAd.vue
css/micro-ad/listing.scss
pages/author/_id.vue
pages/category/_name.vue
pages/section/_name.vue
pages/section/topic.vue
pages/tag/_id.vue

把 `MicroAd` 的樣式移到 `~/css/micro-ad/` 資料夾中，需要的組件再分別引入，原因有三：
- 避免樣式衝突。
- 方便管理。
- 只引入需要的樣式，縮減頁面 CSS 檔案大小。

refactor: move MicroAd listing style to specific folder

---

.babelrc
.eslintrc.js
components/ContainerFullScreenAds.vue
components/ContainerHeader.vue
components/UISearchBar.vue
components/UISearchBarWrapper.vue
components/UIYoutubeSubscribe.vue
components/__tests__/UIArticleListFocus.spec.js
components/__tests__/UISearchBarWrapper.spec.js
components/audio-player/__tests__/ContainerAudioPlayer.spec.js
constants/index.js
deprecated/kc-scroll.js
nuxt.config.js
pages/__tests__/search.spec.js
pages/author/_id.vue
pages/category/_name.vue
pages/search/_keyword.vue
pages/section/_name.vue
pages/section/topic.vue
pages/tag/_id.vue
pages/topic/_id.vue
plugins/gpt-ad/__tests__/gpt-ad.spec.js
plugins/gpt-ad/index.js
plugins/gpt-ad/util.js
plugins/requests/index.js
server/index.js
test/helpers/createWrapperHelper.js

Comments 樣式規範參考自 [Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript#comments)（可以先看對 [ESlint 設定檔](https://github.com/mirror-media/mirror-media-nuxt/pull/238/files#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5)的更改），有幾點要注意：
- ESlint 無法規範多行註解要以 `/**` 開頭，無法自動 fix，這次是手動改，之後盡量統一成這個樣式，但不強制：
```javascript
/**
* 盡量用這一個
*/
/*
** 這是我們之前有用過的
*/
/*
* 假設你用 // 來表示多行註解，ESlint 會幫你改成這樣
*/
```
- ESlint 無法規範多行註解的 `*` 之後要空一格，但就盡量統一，以免影響閱讀：
```javascript
/**
*可以這樣寫，不會報錯，但盡量不要
*/
```
- 為什麼 `multiline-comment-style` 和 `lines-around-comment` 是用 `warn` 而非 `error`？因為有些情況下，我們可能是想把多行程式碼註解掉，但並不是想把它們當成說明的註解，比如在 `pages/__tests__/search.spec.js`  有這段：
```javascript
// test('section title should be null if section query in url not exist', () => {
//   const wrapper = …
```

style: lint comments style

---

plugins/article/href.js

Refs: https://cloud.google.com/storage/docs/static-website\#examples
@bcgodev says:
> 補充一下今天對於 projects 的 index.html 出現的事情，我看了 nginx 並沒有幫 project 加上 index.html 這樣的設定，301 跟 nginx 並沒有關係，而後端也會直接把 request 直接導向 GCS。
> 
> 如果仔細看周子飛 301 到 `http://www.mirrormedia.mg/projects/zhou_zhi_fei/index.html` 的回應的話，也會發現屬於 GCS 的 header。
>
> 參考 https://cloud.google.com/storage/docs/static-website#examples
可以知道是 project 的網址有誤，因為 project 的 GCS 裡是一個目錄而不是檔案，所以 GCS 會回 301 到 `index.html` ，正確的處理方式應該是鏡週刊對於 project 的網址要使用 `http://www.mirrormedia.mg/projects/zhou_zhi_fei/` 而非 `http://www.mirrormedia.mg/projects/zhou_zhi_fei`。
>
> 使用目錄的話，在 GCS 設定正確時，GCS 也會直接回覆 200 與 index.html 的內容而非 301，對於以前有 index.html 的 project 不會有問題，而且還會減少一個轉址，增加瀏覽速度。

fix: use proper url for Google Cloud Storage

---

api/__tests__/helpers.spec.js
api/helpers.js
api/index.js
api/membership-proxy.js
jest.config.js
nuxt.config.js

1. 新增一個 front-end server endpoint `/api/membership`，其功用與 `/api` 相同，只不過後端位址不同與需要加送 authorization header。
2. 由於 `/api/membership` 與 `/api` 功能大致相同，將原本 `~/api/index.js` 的邏輯搬移到 `~/api/helpers.js`  的 `createProxy` 中，供 proxy 功能（單純將 request 原封不動的送至後端，且將 response 原封不動的從後端傳送至前端，沒有太多加工邏輯）的 front-end server endpoint 使用。

feat(api): add /api/membership for membership proxy

---

components/UiStoryContentHandler.vue
server/index.js

**問題**
無法嵌入TikTok 的影片
**原因**
嵌入的時機可分為 client-side 跟 server-side
client-side 由於是使用 `v-html` 的方式插入 script，因此瀏覽器會擋住 script 的執行
server-side 會執行 script，但卻因為有用套件 helmet 做一些防護措施，導致 iframe 出不來
**解決方法**
讓 embedded code 在 server-side 執行，並移除會影響 iframe 顯示的安全措施
對 iframe 加上 `loading="lazy"` 似乎也會影響，故也移除

fix(story): embed iframes

---

components/culture-post/ContainerCulturePost.vue
components/culture-post/UiTheCover.vue

1. 在 premium 情況下(目前以style=wide表示)，story頁若存在影片( heroVideo )，則影片為滿版。
2. 影片寬高與形式已在 local 和 Tin 確認過，在行動裝置中會持續縮窄，在桌機中上下會被部分切除，文字維持壓在影片上。
3. 這張卡片沒有設計稿，版型同目前測試機的滿版圖片：https://nuxt-dev.mirrormedia.mg/story/test_video
4. 後台資料：http://35.189.183.129:3000/keystone/posts/5ab47c34340ca60e00e549dd
5. 卡片連結：https://app.asana.com/0/1199948555976980/1199966228155154/f

feat: show covered video if heroVideo has data

---

components/culture-post/ContainerCulturePost.vue
pages/external/_slug.vue
pages/premium/_slug.vue
pages/story/_slug.vue
pages/video/_id.vue

1. 在與文章相關的頁面、元件之head meta 增加 dable:image ，以提供編輯部dable後台較小的照片縮圖。
2. external頁、premium頁不確定需求，此份PR仍有增加此 meta tag。
3. video 相關縮圖，考量畫質問題，目前改採medium或standard。
需求文件：https://app.asana.com/0/1200021598612109/1200066366547236

feat: add a new meta tag named dable-image to pass tiny images

---

components/culture-post/UiArticleIndex.vue

在索引無內容時，仍會呈現fb與line分享按鈕
需求文件 (Asana)：https://app.asana.com/0/1200072715055847/1200052271701246

fix: display share area when index list is empty

---

components/culture-post/ContainerCulturePost.vue
components/culture-post/UiArticleBody.vue

1. 在 wide 版面增加 magazine 按鈕，並判斷是否為會員，導入不同頁面。
2. 由於按鈕的css和非會員其他版面的按鈕有些差異，因此並未提取為獨立的元件。
需求：https://app.asana.com/0/1200072715055847/1200078750709895 (已修正為wide版型也需要製作，形式與會員一致)
設計：https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E7%B6%B2%E7%AB%99(%E6%9C%83%E5%93%A1)?node-id=1143%3A0

feat: add magazine button to wide page

---

components/UiHeaderNavSection.vue
components/UiSidebar.vue
store/index.js
store/sections.js

1. 在header中的member區塊內，加入「電子雜誌」子區塊，連結到magazine頁。
2. 討論後，決定不改動原section、cms欄位，而是直接寫死加入。
3. 新加入的「電子雜誌」要在member區塊的最上方
需求文件：https://app.asana.com/0/1200072715055847/1200041811234963

feat: add magazine-page entry to member section

---

components/culture-post/UiArticleBody.vue

feat: not display magazine-button if premium-inviting-button exist

---

components/UiArticleList.vue

1. 將「周子飛」專題，由「 /story/ 」改為 「 /projects/ 」
2. 此次僅針對「周子飛」專題進行修改，若要完整解決 projects 文章導向問題，還需和編輯部確認專題文章的使用方式
專題連結：https://www.mirrormedia.mg/projects/zhou_zhi_fei/

fix: redirect to /projects/ especially for zhou_zhi_fei

---

components/PurchasedList.vue
components/SubscribeSimFormStatus.vue
components/SubscribeSuccess.vue
components/SubscribeSuccessOrderInfo.vue
components/SubscribeSuccessOrderInfoContentRow.vue
components/SubscribeSuccessOrderInfoContentRowPurchasedList.vue
components/__tests__/SubscribeSuccessOrderInfo.spec.js
pages/__tests__/subscribe-result.spec.js
pages/subscribe/result/index.vue

重構`SubscribeSuccessOrderInfo.vue` components：
1. （DONE）新增 `customerInfo` props，為從原本的 `orderInfo` 拆分得出，若 `customerInfo` 中所有欄位皆為空值則能做到不顯示顧客資訊區塊，為[新需求](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A-%E7%B6%B2%E7%AB%99?node-id=2866%3A867)要符合的功能。
2. （DONE）修改 `orderInfo` props，使得訂單內容能夠容許進一步的客製化，達到[新需求](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A-%E7%B6%B2%E7%AB%99?node-id=2866%3A867)，預計將會整併訂單編號以及運費等設定到單一 `orderInfo` props 中。
- 已整併的 props：
- 移除 `orderId`，整併至 `orderInfo.orderId`，如此 `SubscribeSuccess` component props 從 `orderInfo`, `orderId`, `customerInfo` 減免為 `orderInfo`, `customInfo`，剛好代表 [UI 上下兩個大分區](https://app.zeplin.io/project/5ac2f13c0f240ab10d2c7dfc/screen/5d6dd8c8fcbfc79bf449fda4)，我認為是比較直覺的介面。
重構 …

feat: redesign props of subscribe success order info

---

components/UiArticleList.vue
utils/article.js

1. 將 type 為 project 的文章，都導向 projects/${slug}。
2. 將原先單獨判斷是否為周子飛文章的函式移除。
- 需求：[Asana](https://app.asana.com/0/1200514764581162/1200520483300762)
- 非本次的修改範圍，但額外遇到的錯誤紀錄。可能是因為在 template 上使用 plugins 注入的函式：
> [Vue warn]: Property or method "$GOExp" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

feat: adjust the redirecting-strategy of articles which type is project

---

components/SubscribeForm.vue
components/SubscribeFormOrdererData.vue

- 當勾選「同訂購人資訊」時，欄位自動填上相同資訊。
- 更改錯誤訊息和 disable 時的狀態。
1. 將 `SubscribeForm` 中的 `ordererData` 和 `setOrdererData` 作為 props 傳入。
2. watch `SubscribeForm` 中各個 input 值，當有變化時若 `type = '訂購人'` ，則用 `setOrdererData` 及時更改 `ordererData`。如此一來便可確保 `ordererData` 永遠保持在最新狀態。
3. 按下「同訂購人資訊」時，若偵測到是打勾（**這裏不知為何 `this.receiverDataIsSameAsOrderer` 必須是 false 而非 true，要麻煩 reviewer 解答了，感謝**），`setDisable()` 可將 component 中的 data 和 `ordererData` 同步。
4. 到上一部為止，我們打勾時可以看到兩者資料同步了，再來為了讓使用者在打勾後就算更改訂購人資料也能及時更新，一但 watch 到 `ordererData` 有更動，也要再同步一次資料。
- [卡片](https://app.asana.com/0/1200570778319695/1200581556792681)

feat: show receiver data when it is same as orderer data

---

components/SubscribeForm.vue
components/SubscribeFormShip.vue
components/UiSubscribeRadioInput.vue

- 預設選項為：一般配送
- 在掛號配送下方增加兩欄總金額說明
- 總金額如果不寫死的話好像較易維護，不過不確定資料該怎麼存？
- [卡片](https://app.asana.com/0/1200570778319695/1200581556792679)

feat: adjust ship method area

---

components/SubscribeFormOrdererData.vue
components/SubscribeFormReceipt.vue
components/UiValidationInput.vue
pages/papermag/_plan/index.vue

- 若沒通過手機驗證，則無法送出
- 新增二聯式發票驗證，沒通過則顯示錯誤 & 無法送出
- 勾選其他發票方式後，二聯式發票單選清空，下方無法輸入
- 更改送出後重導的 url

feat: receipt validation & fix: submit redirect path

---

components/SubscribeForm.vue
components/SubscribeFormPlanList.vue
components/SubscribeFormReceipt.vue
components/SubscribeSuccessOrderInfo.vue

- 續訂折扣碼輸入框格式改成輸入後 8 碼
- 我有續訂折扣碼的文字調整：選擇二年鏡週刊 104 期，應出現 "折扣 80 元，贈送 2 期" (目前顯示 "贈送 1 期" 有邏輯錯誤)
- 若訂購人沒輸入市話資料，打勾同收件人，市話欄位不應帶預設值 (目前會有內容)
- 電子發票底下的文字刪除 "發票將於付款成功後..."
-[Asana卡片](https://app.asana.com/0/1200640136089459/1200683061054603/f)

fix: adjust papermag

---

components/MembershipFormPerchaseInfo.vue
components/SubscribeFail.vue
pages/subscribe/fail.vue
pages/subscribe/info.vue
pages/subscribe/success.vue

- 新增訂閱成功和失敗頁 UI
- 成功頁：/subscribe/success，另有小工具調整按鈕狀況
- 失敗頁：/subscribe/fail
- [Asana 卡片](https://app.asana.com/0/1200720395792829/1200520483300780)
- [會員訂閱頁面 PRD](https://paper.dropbox.com/doc/PRD--BPzlvJ_sLZ33TAcqn4wia7_TAg-r3yPzn9K2wU5fUI5cy37F)
- [設計稿](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A---%E7%B6%B2%E7%AB%99?node-id=2822%3A6801)

feat: membership-subscribe-result page UI

---

components/SubscribeMembershipChoosePlanCard.vue
pages/profile/purchase.vue
pages/subscribe/success.vue

- 成功頁（/subscribe/success）模擬器於正式機隱藏
- 解決方案選擇頁（/subscribe）按鈕於 safari 無法分開問題
- 調整訂閱紀錄頁（/profile/purchase）padding

fix: subscribe UI and sim

---

components/ContainerStoryBody.vue

- 更改文章前言顏色，統一改成藍色
- [設計稿](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A---%E7%B6%B2%E7%AB%99?node-id=3305%3A11987)

style(ContainerStoryBody): brief color

---

pages/subscribe/info.vue

- 會員訂閱確認訂購頁，填入**發票**email欄位需帶預設值，且可被更動

feat: subscribe-info receipt email preset membership email

---

nuxt.config.js
store/membership.js

Determine route name rather than route path, so that we can perform login when the route path is end with `/` like `/login/`.
ref: [Named Routes of Vue Router](https://router.vuejs.org/guide/essentials/named-routes.html)

fix(login-page): resolve login error when route path is not exactly /login

---

components/MemberShipStatus.vue
components/MembershipFormPerchaseInfo.vue
components/MembershipPayRecord.vue
components/MembershipPosts.vue
components/SubscribeFormReceipt.vue
components/SubscribeMembershipChoosePlanCard.vue
components/UiMembershipList.vue
components/UiMembershipPayRecordList.vue
components/UiMerchandiseList.vue
components/UiSubscribeSelect.vue
components/UiValidationInput.vue
pages/subscribe/info.vue
pages/subscribe/success.vue

- 會員訂閱發票二聯式「Email 收據」改成「「電子發票載具」。
- 會員訂閱發票二聯式若「沒選」和「電子發票載具」皆不顯示 input，並自動帶入上方信箱。
- 考量 safari 相容性，將 css 中的 `gap` 改掉。

fix: receipt input and email and css gap remove

---

deprecated/topic-page/Topic.vue

- 需求 (Asana)：https://app.asana.com/0/1200896349481613/1201124118161034
- 描述：移除 `topic` 頁中 `type` 為 `list` 的頁中廣告。
- 補充：目前 `topic` 的分類只有 `timeline`、`group`、`protrait wall`、`list` 四種，在 `topic` 頁的分類中前三者有各自的版面，而 `list` 則被分在 v-else 中，因此若未來有新增 `type `類型，此次修改會被套用。
附錄：[type 為 list 實際文章範例](http://mirrormedia.tw/keystone/topics/614d27fb1347d20f00f112c5)

feat: remove DFPads in topic article list when type is not timeline/group/portrait

---

.dockerignore
cloudbuild.yaml

Related topic: [Feat/add mirror media nuxt and new CD flow](https://github.com/mirror-media/kubernetes-configs/pull/79)
1. `.dockerignore` has ignored files related to cloud build, git, and style rules.
2. A `trigger_deployment` step is added to `cloudbuild.yaml` to trigger deployment. New variables are needed.
3. A secret is used to protect the webhook. It must be retrieved from `secretManager` and applied to shell agrs.
Please see [mm-mirror-media-nuxt-CD](https://console.cloud.google.com/cloud-build/triggers/edit/f0b1dadf-a97f-4bce-bcc2-01fa177190cb?authuser=2&project=mirrormedia-1470651750304)

Feat cd with cloud build
